import type { Metadata } from "next";
import "./globals.css";
import Header from "@/ui/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="grid grid-flow-col grid-cols-[12rem_1fr] h-screen">
          <div className="p-2">Navbar</div>
          <div className="grid grid-flow-row grid-rows-[max-content_1fr_4rem]">
            <div className="p-2">
              <Header />
            </div>
            <div className="grid grid-flow-col grid-cols-[1fr_24rem]">
              <div className="p-2">{children}</div>
              <div className="p-2">right sidebar</div>
            </div>
            <div className="p-2">Footer</div>
          </div>
        </div>
      </body>
    </html>
  );
}
