import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/ui/header";
import Footer from "@/ui/footer";
import Menu from "@/ui/menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Personal Profile Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full w-full">
      <body className={inter.className + " h-full w-full"}>
        <div className="m-4 grid grid-cols-[16rem_1fr] grid-rows-[8rem_1fr_8rem] min-h-full">
          <menu className="m-4 col-span-1 row-span-3">
            <Menu />
          </menu>
          <header className="col-span-1 row-span-1">
            <Header />
          </header>
          <main className="col-span-1 row-span-1">{children}</main>
          <footer className="m-4 col-span-1 row-span-1">
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
