@startuml tool-stack

database "SQLite" as db

package "Personal profile page" {

    component [Next.js] as next
    component [Prisma] as prisma
    component [Tailwind CSS] as tailwind

    next -- prisma
    next - tailwind
}

prisma -- db

@enduml